apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: fkfiroj/laravel-app:latest   # <-- CI এটা SHA দিয়ে auto update করবে
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              value: laravel
            - name: DB_PASSWORD
              value: secret
          volumeMounts:
            - name: storage
              mountPath: /var/www/storage
            - name: cache
              mountPath: /var/www/bootstrap/cache

          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10

      initContainers:
        - name: init-permission
          image: busybox
          command: ['sh', '-c', 'chmod -R 777 /var/www/storage /var/www/bootstrap/cache || true']
          volumeMounts:
            - name: storage
              mountPath: /var/www/storage
            - name: cache
              mountPath: /var/www/bootstrap/cache

      volumes:
        - name: storage
          emptyDir: {}
        - name: cache
          emptyDir: {}
