name: Build, push Docker image and update deployment manifest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }}

      - name: Update deployment manifest image tag now
        run: |
          echo "Updating deployment image tag to ${{ github.sha }}"
          sed -i "s|fkfiroj/laravel-app:.*|fkfiroj/laravel-app:${{ github.sha }}|" k8s/prod/deployment.yaml

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add k8s/prod/deployment.yaml
          git commit -m "Update deployment image tag to ${{ github.sha }}" || echo "No changes to commit"

          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/firoj7github/Laravel-docker-argocd.git HEAD:main
