name: Build, Scan, Push and Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ✅ Checkout source code
    - name: Checkout source code
      uses: actions/checkout@v3

    # ✅ SonarQube Static Analysis
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
      with:
        projectBaseDir: .

    # ✅ SonarQube Quality Gate
    - name: Wait & Check Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

    # ✅ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ✅ Login to Docker Hub Account
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ✅ Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }} .

    # ✅ Trivy Security Scan
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }}
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        ignore-policy: .trivyignore

    # ✅ Push Docker Image (only if Trivy passes)
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }}

    # ✅ Update Kubernetes Deployment YAML with new image SHA
    # - name: Update deployment manifest image tag
    #   run: |
    #     echo "Updating image tag to ${{ github.sha }}"
    #     sed -i "s|fkfiroj/laravel-app:.*|fkfiroj/laravel-app:${{ github.sha }}|" k8s/prod/deployment.yaml

    #     git config --global user.name "github-actions"
    #     git config --global user.email "github-actions@github.com"
    #     git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/firoj7github/Laravel-docker-argocd.git

    #     git add k8s/prod/deployment.yaml
    #     git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
    #     git push origin main
